Add hspec-junit-formatter 1.1.0.1 resolver
freckle/stackage-snapshots pull request #35
Opened 2022-04-18 15:55 UTC by z0isch

When using the new `/lts/19/1.yaml` the following warning happens for `freckle-app`

```
WARNING: Ignoring freckle-app's bounds on hspec-junit-formatter (>=1.1.0.1); using hspec-junit-formatter-1.0.3.0.
Reason: trusting snapshot over cabal file dependency information.
```

We had a case-insensitivity macOS bug for that particular version, so anything depending on this snapshot fails when building on a mac. This adds the v1.1.0.1 of the library to a new `/lts/19/1/FR1.yaml` snapshot.  This does produce a new set of warnings  when running `./bin/check lts/19/1/FR1.yaml `, but I am not sure if this is a problem? I'll build `fancy-api` against this snapshot to ensure that it's working as intended.

```
WARNING: Ignoring ekg-core's bounds on base (>=4.6 && <4.15); using base-4.15.1.0.
Reason: trusting snapshot over cabal file dependency information.
WARNING: Ignoring ekg-core's bounds on ghc-prim (<0.7); using ghc-prim-0.7.0.
Reason: trusting snapshot over cabal file dependency information.
WARNING: Ignoring sendgrid-v3's bounds on base (>=4.8 && <4.15); using base-4.15.1.0.
Reason: trusting snapshot over cabal file dependency information.
```

2022-04-18 16:05 UTC, z0isch commented
Looks like `fancy-api` builds fine on my mac against https://raw.githubusercontent.com/freckle/stackage-snapshots/3068bc93034258d484fd4006fa15852560a81cd5/lts/19/1/FR1.yaml

2022-04-18 16:36 UTC, eborden approved these changes

2022-04-18 17:20 UTC, StevenXL requested changes
@z0isch Please ignore me if this is going to slow you dow, but instead of creating an FR version, do you want to just upgrade to 19/3.yaml? 

https://github.com/freckle/stackage-snapshots/pull/34

The only changes I'd make on #34 is updating the `bytebuild` and `contiguous` libs per linting errors. 

Feel free to ignore.

2022-04-18 18:48 UTC, z0isch commented
> @z0isch Please ignore me if this is going to slow you dow, but instead of creating an FR version, do you want to just upgrade to 19/3.yaml?
> 
> #34
> 
> The only changes I'd make on #34 is updating the `bytebuild` and `contiguous` libs per linting errors.
> 
> Feel free to ignore.

I'd like to address this that way, but as I'm blocked right now I'd like to push this forward as is. I'll see if I can look into the 19.3 changes afterwards

2022-04-18 18:48 UTC, merged

2022-04-18 18:58 UTC, StevenXL commented
> > @z0isch Please ignore me if this is going to slow you dow, but instead of creating an FR version, do you want to just upgrade to 19/3.yaml?
> > #34
> > The only changes I'd make on #34 is updating the `bytebuild` and `contiguous` libs per linting errors.
> > Feel free to ignore.
> 
> I'd like to address this that way, but as I'm blocked right now I'd like to push this forward as is. I'll see if I can look into the 19.3 changes afterwards

No worries - I'll take over that PR.

2022-04-20 14:04 UTC, pbrisbin reviewed
Ugh. Sorry, this is a mess that I've yet to work with the maintainers to fully resolve.

`hspec-junit-formatter` got pinned in `nightly`, because the `freckle-app` in `lts-18` required `< 1.0` and could not support `1.1` without its own major bump (so not allowed) -- all due to this case-sensitivity nonsense. It was discussed that that was fine to keep `1.0` in `lts-18` and then we'd get `1.1` (which worked with latest `freckle-app`) in `lts-19` when the major bumps could all happen.

`lts-19` came out and just got what was in `nightly` (because doing otherwise meant working around that automation), so `1.0`.

I didn't realize and removed this extra-dep when I cut our `lts-19` snapshot, breaking you.

I'm going to figure out our options in [this Issue](https://github.com/commercialhaskell/lts-haskell/issues/340).

2022-04-20 14:04 UTC, pbrisbin commented on lts/19/1/FR1.yaml
> +  - hspec-junit-formatter-1.1.0.1@sha256:0365b3a5aa2e292604826c7cf99ace8b3248a369d8f5821edff9bc1031e16a5c,3853
As per Stackage authors, putting these SHAs here is low value / high effort. So we've stopped (as you can see in all the other deps here).

When a snapshot is eventually used the `.lock` files are written, which include the integrity checks. And now that we commit those, this prevents any security issues when that code is deployed. The SHAs written into the `.lock` file are the same ones generated by the `stack` message that we copy paste into this file -- so it's an equivalent level of security. It's leaves the minor gap that, on first use, something is off and we commit an attackers SHA into the `.lock` file, but I don't think anyone is attempting to avoid that (by manually computing SHAs from source for every dependency we use and committing that), so :shrug: